# Missingness in data

### Install & import packages.

In [1]:
import pandas as pd
import numpy as np
import missingno as msno # You might have to: pip install missingo

### Load datasets from csv.

In [3]:
# Read in all the datasets that you want to perform the missingness analyses on.

#spectral = pd.read_csv("C:/Users/monik/Documents/Paris/Internship/Analyses/Pilot-Data/Big-Sets/spectral_data_ALL_IMPROV_pilots.csv", 
                      # index_col=0).set_index('TIME_FRAME')
                      # Can't specify the argument na_values to '-1', because 
                      # the phase columns contain -1 values which aren't na_values!
# Spectral data
df1 = pd.read_csv("C:/Users/monik/Documents/Paris/Internship/Analyses/Pilot-Data/Keith-2-Data/spectral_data2_ALL_SF_pilots.csv",
                  index_col=0)

### Detect missing data.

In [4]:
# Inspect the columns.
df1.head() # Missing values: empty cells, and NaNs.

,TIME_FRAME,FUNDAMENTAL_FREQUENCY,MIDI_NOTE,NG_type,NG_ID,NG,PARTICIPANT_ID,SONG_ID
0,0.000000,NaN,NaN,NaN,NaN,NaN,111,1
1,0.023238,NaN,NaN,NaN,NaN,NaN,111,1
2,0.046475,NaN,NaN,NaN,NaN,NaN,111,1
3,0.069713,NaN,NaN,NaN,NaN,NaN,111,1
4,0.092950,47.604511,NaN,NaN,NaN,NaN,111,1

In [6]:
df1.describe()

,TIME_FRAME,FUNDAMENTAL_FREQUENCY,MIDI_NOTE,NG_ID,NG,PARTICIPANT_ID,SONG_ID
count,193411.000000,149475.000000,147263.000000,146430.000000,145629.000000,193411.000000,193411.000000
mean,14.966808,239.578352,56.576388,57.571693,56.622112,665.981635,15.499806
std,8.647818,144.770042,7.465366,38.813928,7.501672,313.970425,8.655323
min,0.000000,32.703196,24.000000,0.000000,24.000000,111.000000,1.000000
25%,7.479193,166.728822,52.300000,25.000000,52.300000,555.000000,8.000000
50%,14.965011,222.556277,57.200000,53.000000,57.300000,777.000000,15.000000
75%,22.460807,282.027698,61.300000,84.000000,61.350000,888.000000,23.000000
max,29.950023,2093.004522,93.200000,204.000000,92.700000,999.000000,30.000000

### Analyze the amount and type of missingness.

#### Find any relations of missing to missing values between columns.

In [ ]:
participants = [df1, df5, df7, df8, df9]
df_nullity_all = pd.DataFrame()

for i in participants:
    # Get the nullity in the dataset. True indicates a missing value, False an observed value.
    df_nullity = i.isnull()
    
    # Sum the number of True values in the dataset. 
    df_nullity.sum()

    # Get the percentage of missing data.
    print(df_nullity.mean() * 100)

In [ ]:
msno.bar(df)

In [ ]:
# Get the nullity in the dataset. True indicates a missing value, False an observed value.
df7_nullity = i.isnull()

# Sum the number of True values in the dataset. 
df7_nullity.sum()

# Get the percentage of missing data.
df7_nullity.mean() * 100

In [ ]:
# Plot the completness of data. Missing Completely at Random (MCAR), Missing at Random (MAR) or Missing Not at Random (MNAR) ?
sorted_df = (df1[df1['SONG_ID'] == 4]).sort_values('TIME_FRAME') # CHROMA_ID
msno.matrix(sorted_df) # There is a relationship between missingness and its values! MNAR

                      # can add argument freq='M' for time-series data but
                      # then the index_col must be PeriodIndex or DatetimeIndex

In [ ]:
# Plot the completness of data. Missing Completely at Random (MCAR), Missing at Random (MAR) or Missing Not at Random (MNAR) ?
sorted_df = (df5[df5['SONG_ID'] == 4]).sort_values('TIME_FRAME') # CHROMA_ID
msno.matrix(sorted_df) # There is a relationship between missingness and its values! MNAR

                      # can add argument freq='M' for time-series data but
                      # then the index_col must be PeriodIndex or DatetimeIndex

In [ ]:
# Plot the completness of data. Missing Completely at Random (MCAR), Missing at Random (MAR) or Missing Not at Random (MNAR) ?
sorted_df = (df7[df7['SONG_ID'] == 4]).sort_values('TIME_FRAME') # CHROMA_ID
msno.matrix(sorted_df) # There is a relationship between missingness and its values! MNAR

                      # can add argument freq='M' for time-series data but
                      # then the index_col must be PeriodIndex or DatetimeIndex

In [ ]:
# Plot the completness of data. Missing Completely at Random (MCAR), Missing at Random (MAR) or Missing Not at Random (MNAR) ?
sorted_df = (df8[df8['SONG_ID'] == 4]).sort_values('TIME_FRAME') # CHROMA_ID
msno.matrix(sorted_df) # There is a relationship between missingness and its values! MNAR

                      # can add argument freq='M' for time-series data but
                      # then the index_col must be PeriodIndex or DatetimeIndex

In [ ]:
# Plot the completness of data. Missing Completely at Random (MCAR), Missing at Random (MAR) or Missing Not at Random (MNAR) ?
sorted_df = (df9[df9['SONG_ID'] == 4]).sort_values('TIME_FRAME') # CHROMA_ID
msno.matrix(sorted_df) # There is a relationship between missingness and its values! MNAR

                      # can add argument freq='M' for time-series data but
                      # then the index_col must be PeriodIndex or DatetimeIndex

In [ ]:
# Plot the correlations between missing values in different columns.
# Color indicates the direction and strenght of the correlation.
msno.heatmap(df1)

In [ ]:
msno.heatmap(df5)

In [ ]:
msno.heatmap(df7)

In [ ]:
msno.heatmap(df8)

In [ ]:
msno.heatmap(df9)

#### Find any relation of missing to non-missing values between columns.

In [ ]:
# MORE RELEVANT FOR QUESTIONNAIRE DATA ?!

### Impute missing data.

In [ ]:
# DEPENDS ON THE TYPE OF MISSINGNESS IN THE DATA!